### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by nurislamov** [2gis/makeup#20]
![screen shot 2015-04-06 at 00 47 41](https://cloud.githubusercontent.com/assets/6479637/6998814/93ff5b94-dbf6-11e4-9cec-ef9459e99916.png)

экстр**е**мальных же, ну

**Comment by artem-malko** [comment]
@nurislamov данные с ошибками — это тоже экстремальные данные)

**Comment by Diokuz** [comment]
Спасибо, поправим)

**Comment by Dissimulazione** [comment]
А ещё опечатка «изорбражением» и три разных варианта написания названия «MakeUp» на одной странице. Интересно, какой всё-таки задумывался.

**Comment by Chaptykov** [comment]
Fixed b52c19f5856a38a771b0191232b0e20d4cf5f854
