### ISSUE TITLE
Выполнение скрипта после отрисовки блока

### ISSUE THREAD

**Issue by in19farkt** [2gis/makeup#77]
Привет. 

Подключили Makeup к [стартеркиту](https://github.com/fullstack-development/flat-starter-kit/tree/add_components) на вебпак. Для некоторых компонентов, после отрисовки, нужно выполнять скрипт, чтобы компонент принял окончательный внешний вид (используются jquery плагины). Можно ли среагировать на переключение элемента, чтобы после вставки элемента на страницу его проинициализировать?

Сейчас решили проблему так:
```
import pugTemplate from './index.pug';
import render from '../calendar';

const data = {
  name: 'calendar',
  type: 'module',
  items: [{
    name: 'default.calendar.component',
    type: 'module',
  }]
};

function template({module: blockName}) {
  switch (blockName) {
    case 'default.calendar.component': {
      setTimeout(() => {render()}, 300);
      return pugTemplate({});
    }
  }
}

export {
  data,
  template,
}
```
здесь функцию `render()` нужно выполнить после отрисовки блока `default.calendar.component`.

**Comment by Chaptykov** [comment]
Привет!

В объекте с данными вы можете для любого уровня вложенности указать поле `snippet`, значением которого должна быть функция. 

После инициализации компонента, выполнятся все сниппеты [по цепочке вложенности](https://github.com/2gis/makeup/blob/master/source/js/makeup.js#L672).

Например, для таких данных:

```js
var data = {
  label: 'Project',
  snippet: () => console.log(1),
  items: [
    {
      name: 'component',
      snippet: () => console.log(2)
    }
  ]
}
```

После отрисовки блока, в консоли выведется:

```
1
2
```

**Comment by in19farkt** [comment]
Спасибо :)
